import React,{useState}from'react';
import{StatusBar}from'expo-status-bar';
import{SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView,Platform,TextInput,Image,Linking}from'react-native';

const C={navy:'#031c31',navy2:'#082a47',garnet:'#8d2037',gold:'#d6ad58',white:'#fff',muted:'#9db0c2',paper:'#061a2b'};
const LOGO='https://media.api-sports.io/football/teams/1628.png';
const stories=[
 {id:1,cat:'CLUBE',date:'21 SET 2026',title:'Estreia de sonho na Liga Europa',lead:'O Torreense entrou com o pé direito na Liga Europa, vencendo por 2-1 na Noruega.',body:['Na noite da passada quinta-feira, a equipa azul-grená fez a sua estreia nas competições europeias com uma vitória por 2-1 frente ao Lillestrøm, somando os primeiros três pontos.','Alejandro Alfaro inaugurou o marcador aos 23 minutos e Manuel Pozo ampliou a vantagem aos 49. O Lillestrøm reduziu aos 79 minutos, mas o Torreense segurou uma vitória histórica.','A equipa volta às noites europeias a 15 de outubro, frente ao Sunderland, no Estádio Municipal de Leiria.'],url:'https://www.torreense.com/blog/estreialigaeuropa'},
 {id:2,cat:'FUTEBOL',date:'18 SET 2026',title:'Lillestrøm SK x SCU Torreense - Convocados',lead:'Consulta a informação da equipa para a jornada europeia.',body:['Informação oficial do SCU Torreense relativa à convocatória para o encontro europeu.'],url:'https://www.torreense.com/blog'},
 {id:3,cat:'FUTEBOL',date:'17 SET 2026',title:'Lillestrøm SK x SCU Torreense - Informações Úteis',lead:'Informações para os adeptos que acompanham a equipa.',body:['Informação oficial destinada aos adeptos do SCU Torreense para a deslocação europeia.'],url:'https://www.torreense.com/blog'},
 {id:4,cat:'CLUBE',date:'11 SET 2026',title:'Informação sobre bilhética - Lillestrøm SK x SCU Torreense',lead:'Informação oficial de bilhética.',body:['Consulta os detalhes de bilhética disponibilizados pelo clube.'],url:'https://www.torreense.com/blog/informacaobileticaligaeuropa'}
];
function Logo({size=58}){return <Image source={{uri:LOGO}} style={{width:size,height:size,resizeMode:'contain'}}/>}
function Login({guest,login}){return <ScrollView contentContainerStyle={s.login}><Logo size={105}/><Text style={s.brand}>SPORT CLUBE</Text><Text style={s.brandStrong}>UNIÃO TORREENSE</Text><Text style={s.since}>TORRES VEDRAS · DESDE 1917</Text><View style={s.loginBox}><Text style={s.loginTitle}>Bem-vindo</Text><Text style={s.loginDesc}>Entra na tua conta Torreense ou continua a explorar como adepto.</Text><TextInput style={s.input} placeholder="Email ou nº de sócio" placeholderTextColor="#718395"/><TextInput style={s.input} placeholder="Palavra-passe" placeholderTextColor="#718395" secureTextEntry/><Pressable style={s.redBtn} onPress={login}><Text style={s.btnText}>ENTRAR</Text></Pressable><Pressable style={s.guestBtn} onPress={guest}><Text style={s.guestText}>CONTINUAR SEM LOGIN</Text></Pressable></View></ScrollView>}
function Header({anon,onLogin}){return <View style={s.header}><Logo/><View style={{flex:1}}><Text style={s.hSmall}>SPORT CLUBE</Text><Text style={s.hBig}>UNIÃO TORREENSE</Text><Text style={s.hSince}>TORRES VEDRAS · DESDE 1917</Text></View>{anon?<Pressable onPress={onLogin}><Text style={s.enter}>ENTRAR</Text></Pressable>:<View style={s.avatar}><Text style={{color:'white',fontWeight:'900'}}>RS</Text></View>}</View>}
function Home({anon,onLogin,go,openStory}){return <ScrollView contentContainerStyle={s.content}><Header anon={anon} onLogin={onLogin}/><View style={s.matchCard}><View style={s.matchTop}><View><Text style={s.competition}>LIGA PORTUGAL MEU SUPER</Text><Text style={s.jornada}>Jornada 7</Text></View><Text style={s.date}>10 OUT · 15:30</Text></View><View style={s.teams}><View style={s.team}><View style={s.tdf}><Text style={s.tdfText}>CDT</Text></View><Text style={s.teamName}>CD TONDELA</Text></View><Text style={s.vs}>VS</Text><View style={s.team}><Logo size={74}/><Text style={s.teamName}>SCU TORREENSE</Text></View></View><Text style={s.venue}>⌖  Estádio João Cardoso</Text><Pressable style={s.redBtn} onPress={()=>go('Jogos')}><Text style={s.btnText}>🎟  VER JOGO</Text></Pressable></View>
 <View style={s.quickRow}>{[['🎟','BILHETES'],['▣','TORRES PASS'],['♙','SÓCIO'],['▱','LOJA']].map(x=><View key={x[1]} style={s.quick}><Text style={s.quickIcon}>{x[0]}</Text><Text style={s.quickText}>{x[1]}</Text></View>)}</View>
 <View style={s.sectionHead}><Text style={s.section}>Últimas notícias</Text><Text style={s.more}>VER TODAS ›</Text></View>
 <Pressable style={s.feature} onPress={()=>openStory(stories[0])}><View style={s.featureArt}><Logo size={100}/></View><View style={s.featureBody}><Text style={s.tag}>{stories[0].cat}</Text><Text style={s.storyDate}>{stories[0].date}</Text><Text style={s.featureTitle}>{stories[0].title}</Text><Text style={s.lead}>{stories[0].lead}</Text><Text style={s.read}>LER NA APP  ›</Text></View></Pressable>
 {stories.slice(1).map(n=><Pressable key={n.id} style={s.storyRow} onPress={()=>openStory(n)}><View style={s.storyLogo}><Logo size={45}/></View><View style={{flex:1}}><Text style={s.tag}>{n.cat}</Text><Text style={s.rowTitle}>{n.title}</Text><Text style={s.storyDate}>{n.date}</Text></View><Text style={s.chev}>›</Text></Pressable>)}
 <View style={s.dataNote}><Text style={s.dataTitle}>DADOS DESPORTIVOS</Text><Text style={s.dataText}>Jogos, resultados, classificações, plantel e estatísticas preparados para sincronização com API-Football.</Text></View></ScrollView>}
function Article({item,back}){return <ScrollView contentContainerStyle={s.content}><Pressable onPress={back}><Text style={s.back}>‹ VOLTAR</Text></Pressable><View style={s.articleHero}><Logo size={110}/></View><Text style={s.tag}>{item.cat}</Text><Text style={s.articleDate}>{item.date}</Text><Text style={s.articleTitle}>{item.title}</Text><Text style={s.articleLead}>{item.lead}</Text>{item.body.map((p,i)=><Text key={i} style={s.paragraph}>{p}</Text>)}<Pressable style={s.original} onPress={()=>Linking.openURL(item.url)}><Text style={s.originalText}>VER NOTÍCIA ORIGINAL EM TORREENSE.COM ↗</Text></Pressable></ScrollView>}
function Games({anon,onLogin}){return <ScrollView contentContainerStyle={s.content}><Header anon={anon} onLogin={onLogin}/><Text style={s.section}>Jogos</Text><Text style={s.sub}>Equipa Principal · 2026/27</Text>{[['11 SET','SCU Torreense','0 — 0','Leixões SC'],['10 OUT','CD Tondela','15:30','SCU Torreense'],['26 OUT','SCU Torreense','—','Amarante F.C.']].map(x=><View style={s.game} key={x[0]}><Text style={s.gameDate}>{x[0]}</Text><View style={{flex:1}}><Text style={s.gameTeam}>{x[1]}</Text><Text style={s.gameTeam}>{x[3]}</Text></View><Text style={s.score}>{x[2]}</Text></View>)}</ScrollView>}
function Private({name,onLogin}){return <View style={s.content}><View style={s.private}><Logo size={90}/><Text style={s.section}>{name}</Text><Text style={s.privateText}>Inicia sessão para aceder a esta área.</Text><Pressable style={[s.redBtn,{width:'100%'}]} onPress={onLogin}><Text style={s.btnText}>ENTRAR</Text></Pressable></View></View>}
export default function App(){const[session,setSession]=useState('login'),[tab,setTab]=useState('Início'),[article,setArticle]=useState(null);if(session==='login')return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.phone}><Login guest={()=>setSession('guest')} login={()=>setSession('user')}/></View></SafeAreaView>;const anon=session==='guest',onLogin=()=>setSession('login');let body=article?<Article item={article} back={()=>setArticle(null)}/>:tab==='Início'?<Home anon={anon} onLogin={onLogin} go={setTab} openStory={setArticle}/>:tab==='Jogos'?<Games anon={anon} onLogin={onLogin}/>:<Private name={tab} onLogin={onLogin}/>;return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.phone}>{body}{!article&&<View style={s.nav}>{[['⌂','Início'],['⚽','Jogos'],['🎟','Bilhetes'],['♙','Sócio'],['☰','Mais']].map(x=><Pressable key={x[1]} style={s.navItem} onPress={()=>setTab(x[1])}><Text style={[s.navIcon,tab===x[1]&&s.active]}>{x[0]}</Text><Text style={[s.navText,tab===x[1]&&s.active]}>{x[1]}</Text></Pressable>)}</View>}</View></SafeAreaView>}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:'#020f1b',alignItems:'center'},phone:{flex:1,width:'100%',maxWidth:520,backgroundColor:C.paper,...Platform.select({web:{boxShadow:'0 0 45px rgba(0,0,0,.4)'}})},content:{padding:18,paddingBottom:105},login:{flexGrow:1,backgroundColor:C.navy,alignItems:'center',justifyContent:'center',padding:24},brand:{color:'#fff',fontSize:20,letterSpacing:2,marginTop:12},brandStrong:{color:'#fff',fontSize:25,fontWeight:'900',letterSpacing:1},since:{color:C.gold,fontSize:10,letterSpacing:2,marginTop:7},loginBox:{width:'100%',backgroundColor:C.navy2,padding:22,borderRadius:22,marginTop:30,borderWidth:1,borderColor:'#27445d'},loginTitle:{color:'#fff',fontSize:26,fontWeight:'900'},loginDesc:{color:C.muted,lineHeight:19,marginVertical:10},input:{height:52,borderRadius:11,backgroundColor:'#0b2236',borderWidth:1,borderColor:'#29445b',paddingHorizontal:14,color:'#fff',marginTop:10},redBtn:{backgroundColor:C.garnet,minHeight:52,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:14},btnText:{color:'#fff',fontWeight:'900',letterSpacing:.5},guestBtn:{padding:17,alignItems:'center'},guestText:{color:C.gold,fontWeight:'800',fontSize:11},
 header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:20},hSmall:{color:'#d7e0e7',fontSize:11,letterSpacing:1.5},hBig:{color:'#fff',fontWeight:'900',fontSize:17},hSince:{color:C.gold,fontSize:8,letterSpacing:1.4,marginTop:3},enter:{color:'#fff',fontWeight:'900'},avatar:{width:40,height:40,borderRadius:12,borderWidth:1,borderColor:'#496075',alignItems:'center',justifyContent:'center'},
 matchCard:{backgroundColor:C.navy2,borderRadius:20,padding:18,borderWidth:1,borderColor:'#29465e'},matchTop:{flexDirection:'row',justifyContent:'space-between'},competition:{color:'#b8c9d7',fontSize:10,fontWeight:'800',letterSpacing:1},jornada:{color:'#fff',fontSize:12,marginTop:5},date:{color:'#fff',fontWeight:'900',fontSize:12},teams:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:20},team:{width:'39%',alignItems:'center'},teamName:{color:'#fff',fontSize:11,fontWeight:'900',marginTop:8,textAlign:'center'},vs:{color:'#8ca2b5',fontWeight:'900',fontSize:18},tdf:{width:65,height:65,borderRadius:33,backgroundColor:'#f5d326',borderWidth:8,borderColor:'#18824a',alignItems:'center',justifyContent:'center'},tdfText:{fontWeight:'900',color:'#17452f'},venue:{color:'#b7c6d2',textAlign:'center',fontSize:12},
 quickRow:{flexDirection:'row',justifyContent:'space-between',marginTop:14},quick:{width:'23%',backgroundColor:C.navy2,borderWidth:1,borderColor:'#29465e',borderRadius:14,alignItems:'center',paddingVertical:15},quickIcon:{color:C.gold,fontSize:21},quickText:{color:'#fff',fontWeight:'800',fontSize:8,marginTop:7},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:28,marginBottom:13},section:{color:'#fff',fontSize:32,fontWeight:'900'},more:{color:'#fff',fontSize:9,fontWeight:'900'},feature:{backgroundColor:C.navy2,borderRadius:18,overflow:'hidden',borderWidth:1,borderColor:'#29465e'},featureArt:{height:150,backgroundColor:C.garnet,alignItems:'center',justifyContent:'center'},featureBody:{padding:16},tag:{alignSelf:'flex-start',backgroundColor:C.garnet,color:'#fff',fontSize:8,fontWeight:'900',paddingHorizontal:8,paddingVertical:4,borderRadius:6},storyDate:{color:C.muted,fontSize:9,marginTop:6},featureTitle:{color:'#fff',fontSize:21,fontWeight:'900',marginTop:8},lead:{color:'#c1ced8',lineHeight:19,marginTop:7,fontSize:12},read:{color:C.gold,fontWeight:'900',fontSize:9,marginTop:12},storyRow:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:C.navy2,borderWidth:1,borderColor:'#29465e',borderRadius:15,padding:11,marginTop:9},storyLogo:{width:62,height:62,borderRadius:10,backgroundColor:'#102f49',alignItems:'center',justifyContent:'center'},rowTitle:{color:'#fff',fontWeight:'800',fontSize:12,marginTop:5},chev:{color:C.muted,fontSize:25},dataNote:{marginTop:18,borderTopWidth:1,borderTopColor:'#29465e',paddingTop:14},dataTitle:{color:C.gold,fontSize:9,fontWeight:'900',letterSpacing:1},dataText:{color:C.muted,fontSize:10,lineHeight:16,marginTop:4},
 back:{color:C.gold,fontWeight:'900',marginVertical:10},articleHero:{height:190,borderRadius:20,backgroundColor:C.garnet,alignItems:'center',justifyContent:'center',marginBottom:18},articleDate:{color:C.muted,fontSize:10,marginTop:10},articleTitle:{color:'#fff',fontSize:30,fontWeight:'900',lineHeight:34,marginTop:8},articleLead:{color:'#d1dbe3',fontSize:17,lineHeight:25,marginVertical:18},paragraph:{color:'#c1ced8',fontSize:14,lineHeight:23,marginBottom:14},original:{borderWidth:1,borderColor:C.gold,borderRadius:12,padding:15,marginTop:10},originalText:{color:C.gold,fontWeight:'900',fontSize:10,textAlign:'center'},
 sub:{color:C.muted,marginTop:4,marginBottom:16},game:{flexDirection:'row',alignItems:'center',backgroundColor:C.navy2,borderRadius:14,padding:15,marginTop:9,borderWidth:1,borderColor:'#29465e'},gameDate:{color:C.gold,fontSize:9,fontWeight:'900',width:50},gameTeam:{color:'#fff',fontWeight:'700',fontSize:12,marginVertical:2},score:{color:'#fff',fontWeight:'900'},private:{marginTop:90,alignItems:'center'},privateText:{color:C.muted,marginVertical:15},
 nav:{position:'absolute',bottom:0,left:0,right:0,height:78,backgroundColor:'#041727',borderTopWidth:1,borderTopColor:'#29465e',flexDirection:'row',justifyContent:'space-around',alignItems:'center',paddingBottom:6},navItem:{alignItems:'center',padding:8},navIcon:{fontSize:18,color:'#8195a7'},navText:{fontSize:8,fontWeight:'800',color:'#8195a7',marginTop:3},active:{color:'#b72c46'}
});