import React, { useState } from 'react';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaView, View, Text, Pressable, StyleSheet, ScrollView, Platform, TextInput, Linking } from 'react-native';

const C={blue:'#073b63',garnet:'#7b1f32',gold:'#c7a45a',ink:'#101820',paper:'#f4f5f6'};
const news=[
 {cat:'CLUBE',date:'21 SET',title:'Estreia de sonho na Liga Europa',desc:'Vitória histórica por 2-1 frente ao Lillestrøm na estreia europeia.',url:'https://www.torreense.com/blog/estreialigaeuropa'},
 {cat:'FUTEBOL',date:'18 SET',title:'Lillestrøm SK x SCU Torreense - Convocados',desc:'Os convocados para a estreia do Torreense na UEFA Europa League.',url:'https://www.torreense.com/blog'},
 {cat:'FUTEBOL',date:'17 SET',title:'Lillestrøm SK x SCU Torreense - Informações Úteis',desc:'Informação para os adeptos que acompanham a equipa.',url:'https://www.torreense.com/blog'},
 {cat:'CLUBE',date:'11 SET',title:'Informação sobre bilhética - Lillestrøm SK x SCU Torreense',desc:'Informações oficiais de bilhética para a deslocação europeia.',url:'https://www.torreense.com/blog/informacaobileticaligaeuropa'}
];
function Crest({small=false}){return <View style={[s.crest,small&&{width:43,height:52,borderRadius:15}]}><View style={s.crestSplit}><View style={{flex:1,backgroundColor:C.garnet}}/><View style={{flex:1,backgroundColor:C.blue}}/></View><Text style={[s.crestText,small&&{fontSize:13}]}>SCUT</Text></View>}
function Login({guest,login}){return <ScrollView contentContainerStyle={s.login}>
 <View style={s.brand}><Crest/><Text style={s.brandName}>SCU TORREENSE</Text><Text style={s.brandSub}>A paixão de Torres Vedras</Text></View>
 <View style={s.panel}><Text style={s.loginTitle}>Bem-vindo à família</Text><Text style={s.loginDesc}>Entra para aceder aos teus bilhetes, Torres Pass, cartão de sócio e benefícios.</Text>
 <TextInput style={s.input} placeholder="Email ou nº de sócio" placeholderTextColor="#8b9095"/><TextInput style={s.input} placeholder="Palavra-passe" placeholderTextColor="#8b9095" secureTextEntry/>
 <Pressable style={s.mainBtn} onPress={login}><Text style={s.mainBtnText}>ENTRAR</Text></Pressable><Pressable style={s.create}><Text style={s.createText}>Criar conta</Text></Pressable>
 <View style={s.sep}><View style={s.line}/><Text style={s.sepText}>OU</Text><View style={s.line}/></View>
 <Pressable style={s.guest} onPress={guest}><Text style={s.guestTitle}>Continuar como adepto</Text><Text style={s.guestText}>Acede a notícias, jogos e informação sem iniciar sessão</Text></Pressable>
 </View></ScrollView>}
function Top({anonymous,onLogin}){return <View style={s.top}><Crest small/><View style={{flex:1}}><Text style={s.topName}>SCU TORREENSE</Text><Text style={s.topTag}>AZUL • GRENÁ</Text></View>{anonymous?<Pressable onPress={onLogin} style={s.enter}><Text style={s.enterText}>ENTRAR</Text></Pressable>:<View style={s.avatar}><Text style={{fontWeight:'800'}}>RS</Text></View>}</View>}
function Home({anonymous,onLogin,go}){return <ScrollView contentContainerStyle={s.content}><Top anonymous={anonymous} onLogin={onLogin}/>
 <View style={s.hero}><Text style={s.heroEyebrow}>PRÓXIMO JOGO · LIGA MEU SUPER</Text><Text style={s.heroDate}>10 OUT · 15:30</Text><View style={s.match}><View style={s.team}><View style={[s.teamMark,{backgroundColor:'#f0c92e'}]}/><Text style={s.teamName}>CD TONDELA</Text></View><View><Text style={s.vs}>VS</Text><Text style={s.round}>J7</Text></View><View style={s.team}><Crest small/><Text style={s.teamName}>TORREENSE</Text></View></View><Text style={s.stadium}>Estádio João Cardoso</Text><Pressable style={s.heroBtn} onPress={()=>go('Jogos')}><Text style={s.heroBtnText}>VER JOGO</Text></Pressable></View>
 <View style={s.shortcuts}>{[['🎟','BILHETES'],['♜','TORRES PASS'],['♙','SÓCIO'],['🛍','LOJA']].map(([i,t])=><Pressable key={t} style={s.short}><Text style={s.shortIcon}>{i}</Text><Text style={s.shortText}>{t}</Text></Pressable>)}</View>
 <View style={s.sectionHead}><Text style={s.sectionTitle}>Últimas notícias</Text><Pressable onPress={()=>Linking.openURL('https://www.torreense.com/blog')}><Text style={s.all}>VER TODAS</Text></Pressable></View>
 <Pressable style={s.leadNews} onPress={()=>Linking.openURL(news[0].url)}><View style={s.newsVisual}><View style={s.newsVisualBlue}/><View style={s.newsVisualGarnet}/><Crest/></View><View style={s.leadBody}><Text style={s.newsMeta}>{news[0].cat} · {news[0].date}</Text><Text style={s.leadTitle}>{news[0].title}</Text><Text style={s.newsDesc}>{news[0].desc}</Text></View></Pressable>
 {news.slice(1).map(n=><Pressable key={n.title} style={s.newsRow} onPress={()=>Linking.openURL(n.url)}><View style={s.newsDate}><Text style={s.newsDay}>{n.date.split(' ')[0]}</Text><Text style={s.newsMonth}>{n.date.split(' ')[1]}</Text></View><View style={{flex:1}}><Text style={s.newsMeta}>{n.cat}</Text><Text style={s.rowTitle}>{n.title}</Text></View><Text style={s.arrow}>›</Text></Pressable>)}
 <Text style={s.source}>Conteúdo editorial: torreense.com</Text>
 </ScrollView>}
function Games({anonymous,onLogin}){return <ScrollView contentContainerStyle={s.content}><Top anonymous={anonymous} onLogin={onLogin}/><Text style={s.pageTitle}>Jogos</Text><Text style={s.pageSub}>Equipa Principal · 2026/27</Text>
 {[['10 OUT','CD Tondela','SCU Torreense','15:30'],['26 OUT','SCU Torreense','Amarante F.C.','—'],['31 OUT','Portimonense SC','SCU Torreense','—']].map(x=><View style={s.gameCard} key={x[0]}><Text style={s.gameDate}>{x[0]}</Text><View style={{flex:1}}><Text style={s.gameTeam}>{x[1]}</Text><Text style={s.gameTeam}>{x[2]}</Text></View><Text style={s.gameTime}>{x[3]}</Text></View>)}</ScrollView>}
function Locked({title,onLogin}){return <View style={s.content}><Top anonymous onLogin={onLogin}/><View style={s.lock}><Text style={s.lockIcon}>♙</Text><Text style={s.pageTitle}>{title}</Text><Text style={s.lockText}>Esta área é exclusiva para adeptos autenticados e sócios Torreense.</Text><Pressable style={s.mainBtn} onPress={onLogin}><Text style={s.mainBtnText}>ENTRAR</Text></Pressable></View></View>}
export default function App(){const[session,setSession]=useState('login');const[tab,setTab]=useState('Início');if(session==='login')return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.phone}><Login guest={()=>{setSession('guest');setTab('Início')}} login={()=>{setSession('user');setTab('Início')}}/></View></SafeAreaView>;const anon=session==='guest',onLogin=()=>setSession('login');let body=tab==='Início'?<Home anonymous={anon} onLogin={onLogin} go={setTab}/>:tab==='Jogos'?<Games anonymous={anon} onLogin={onLogin}/>:anon?<Locked title={tab} onLogin={onLogin}/>:<Locked title={tab} onLogin={onLogin}/>;return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.phone}>{body}<View style={s.nav}>{[['⌂','Início'],['⚽','Jogos'],['🎟','Bilhetes'],['♙','Sócio'],['☰','Mais']].map(([i,t])=><Pressable key={t} style={s.navItem} onPress={()=>setTab(t)}><Text style={[s.navIcon,tab===t&&s.active]}>{i}</Text><Text style={[s.navText,tab===t&&s.active]}>{t}</Text></Pressable>)}</View></View></SafeAreaView>}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:'#e9ecef',alignItems:'center'},phone:{flex:1,width:'100%',maxWidth:520,backgroundColor:C.paper,...Platform.select({web:{boxShadow:'0 0 40px rgba(0,0,0,.15)'}})},content:{padding:18,paddingBottom:105},
 crest:{width:70,height:84,borderRadius:23,overflow:'hidden',borderWidth:3,borderColor:C.gold,alignItems:'center',justifyContent:'flex-end',backgroundColor:'white'},crestSplit:{position:'absolute',left:0,right:0,top:0,bottom:0,flexDirection:'row'},crestText:{color:'#fff',fontWeight:'900',fontSize:18,marginBottom:9,textShadowColor:'#000',textShadowRadius:3},
 login:{flexGrow:1,backgroundColor:C.blue,padding:22,justifyContent:'center'},brand:{alignItems:'center',marginBottom:26},brandName:{color:'#fff',fontSize:25,fontWeight:'900',letterSpacing:1.5,marginTop:12},brandSub:{color:'#b9cbd8',marginTop:4},panel:{backgroundColor:'#fff',borderRadius:28,padding:23},loginTitle:{fontSize:27,fontWeight:'900',color:C.ink},loginDesc:{color:'#6c747b',lineHeight:20,marginTop:7,marginBottom:20},input:{height:53,borderRadius:13,borderWidth:1,borderColor:'#dfe2e4',paddingHorizontal:15,marginBottom:11,backgroundColor:'#fafafa'},mainBtn:{height:53,borderRadius:13,backgroundColor:C.garnet,alignItems:'center',justifyContent:'center'},mainBtnText:{color:'#fff',fontWeight:'900',letterSpacing:.7},create:{alignItems:'center',padding:15},createText:{color:C.blue,fontWeight:'800'},sep:{flexDirection:'row',alignItems:'center',gap:10},line:{height:1,backgroundColor:'#e1e3e5',flex:1},sepText:{fontSize:10,color:'#92979b'},guest:{backgroundColor:'#f1f3f4',padding:15,borderRadius:14,marginTop:14,alignItems:'center'},guestTitle:{fontWeight:'900',color:C.blue},guestText:{fontSize:11,color:'#73797e',marginTop:4,textAlign:'center'},
 top:{flexDirection:'row',alignItems:'center',gap:11,marginBottom:18},topName:{fontSize:18,fontWeight:'900',color:C.blue,letterSpacing:.5},topTag:{fontSize:9,fontWeight:'800',color:C.garnet,letterSpacing:1.5,marginTop:2},enter:{borderWidth:1,borderColor:C.blue,borderRadius:18,paddingHorizontal:13,paddingVertical:8},enterText:{color:C.blue,fontSize:10,fontWeight:'900'},avatar:{width:38,height:38,borderRadius:19,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},
 hero:{backgroundColor:C.blue,borderRadius:25,padding:20},heroEyebrow:{color:'#a9c1d1',fontSize:10,fontWeight:'900',letterSpacing:1.2},heroDate:{color:'#fff',fontSize:17,fontWeight:'900',marginTop:6},match:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginVertical:21},team:{alignItems:'center',width:'37%'},teamMark:{width:43,height:43,borderRadius:22,borderWidth:5,borderColor:'#25823b'},teamName:{color:'#fff',fontSize:11,fontWeight:'900',textAlign:'center',marginTop:9},vs:{color:'#fff',fontWeight:'900',fontSize:18,textAlign:'center'},round:{color:'#8daabc',fontSize:9,textAlign:'center',marginTop:3},stadium:{color:'#c4d3dd',fontSize:11,textAlign:'center'},heroBtn:{backgroundColor:C.garnet,borderRadius:12,padding:13,alignItems:'center',marginTop:16},heroBtnText:{color:'#fff',fontWeight:'900',fontSize:11},
 shortcuts:{flexDirection:'row',justifyContent:'space-between',marginTop:14},short:{width:'23%',backgroundColor:'#fff',borderRadius:15,paddingVertical:14,alignItems:'center'},shortIcon:{fontSize:20},shortText:{fontSize:8,fontWeight:'900',color:C.blue,marginTop:6},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:28,marginBottom:13},sectionTitle:{fontSize:22,fontWeight:'900',color:C.ink},all:{fontSize:9,fontWeight:'900',color:C.garnet},
 leadNews:{backgroundColor:'#fff',borderRadius:20,overflow:'hidden'},newsVisual:{height:145,backgroundColor:C.blue,alignItems:'center',justifyContent:'center',overflow:'hidden'},newsVisualBlue:{position:'absolute',left:0,top:0,bottom:0,width:'58%',backgroundColor:C.blue,transform:[{skewX:'-12deg'}]},newsVisualGarnet:{position:'absolute',right:0,top:0,bottom:0,width:'48%',backgroundColor:C.garnet},leadBody:{padding:16},newsMeta:{fontSize:9,fontWeight:'900',color:C.garnet,letterSpacing:1},leadTitle:{fontSize:20,fontWeight:'900',color:C.ink,marginTop:7},newsDesc:{fontSize:12,color:'#697177',lineHeight:18,marginTop:6},newsRow:{flexDirection:'row',alignItems:'center',backgroundColor:'#fff',borderRadius:16,padding:13,marginTop:9,gap:12},newsDate:{width:42,height:42,borderRadius:11,backgroundColor:C.blue,alignItems:'center',justifyContent:'center'},newsDay:{color:'#fff',fontWeight:'900',fontSize:14},newsMonth:{color:'#b8cad6',fontWeight:'800',fontSize:8},rowTitle:{fontSize:12,fontWeight:'800',color:C.ink,marginTop:3},arrow:{fontSize:25,color:'#a2a6a9'},source:{fontSize:9,color:'#999',textAlign:'center',marginTop:18},
 pageTitle:{fontSize:28,fontWeight:'900',color:C.ink},pageSub:{color:'#747b80',marginTop:3,marginBottom:18},gameCard:{flexDirection:'row',alignItems:'center',backgroundColor:'#fff',borderRadius:17,padding:17,marginBottom:9,gap:14},gameDate:{fontSize:10,fontWeight:'900',color:C.garnet,width:45},gameTeam:{fontSize:13,fontWeight:'800',marginVertical:2},gameTime:{fontWeight:'900',color:C.blue},lock:{marginTop:50,alignItems:'center',backgroundColor:'#fff',padding:28,borderRadius:22},lockIcon:{fontSize:40,color:C.blue},lockText:{color:'#747b80',textAlign:'center',lineHeight:20,marginVertical:15},
 nav:{position:'absolute',bottom:0,left:0,right:0,height:78,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e4e6e8',flexDirection:'row',justifyContent:'space-around',alignItems:'center',paddingBottom:6},navItem:{alignItems:'center',padding:8},navIcon:{fontSize:18,color:'#92979b'},navText:{fontSize:8,fontWeight:'800',color:'#92979b',marginTop:3},active:{color:C.garnet}
});